
# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4a858851e5f429c62b646e456f2a26d9"
application_url = "https://rbp-app-staging.fly.dev"
embedded = true
name = "rbp-app-staging"
handle = "rbp-app-staging"

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = ["app/scopes_update"]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/data_request"]
  uri = "/webhooks/customers/data-request"

  [[webhooks.subscriptions]]
  compliance_topics = ["customers/redact"]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  compliance_topics = ["shop/redact"]
  uri = "/webhooks/shop/redact"

  [[webhooks.subscriptions]]
  topics = ["products/create"]
  uri = "/webhooks/products/create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_metaobjects,write_metaobjects"

[auth]
redirect_urls = [
  "https://rbp-app-staging.fly.dev/auth/callback",
  "https://rbp-app-staging.fly.dev/auth/shopify/callback",
  "https://rbp-app-staging.fly.dev/api/auth/callback"
]

[pos]
embedded = false
